title: TODKAR, Shreedhar Savant  # Add a space after the period

logo: profile.jpg # Use a relative path to logo image 

description: R&D Technical Project Leader | PhD in AI & signal processing # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

email: shreedhar.todkar@gmail.com # Allow visitors to contact you
